[package]
name = "yoyo-mpv"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
mpv-runtime = ["dep:libmpv-sys"]

[dependencies]
libmpv-sys = { version = "3.1.0", optional = true }
thiserror = "2.0.18"
tracing = "0.1.44"
yoyo-core = { path = "../yoyo-core" }
