use std::path::PathBuf;

use crate::{FrameStepDirection, VideoAdjustmentKind, VideoFilterPreset};

#[derive(Debug, Clone, PartialEq)]
pub enum AppCommand {
    OpenFile(PathBuf),
    OpenFolder(PathBuf),
    OpenUrl(String),
    TogglePause,
    SeekRelative(f64),
    SeekAbsolute(f64),
    SetSpeed(f32),
    ResetSpeed,
    SetVolume(u8),
    AdjustVolume(i8),
    CycleAudioChannel,
    RotateClockwise,
    ZoomIn,
    ZoomOut,
    SetABLoopPointA,
    SetABLoopPointB,
    ClearABLoop,
    ToggleFullscreen,
    NextItem,
    PreviousItem,
    SelectAudioTrack(i64),
    SelectSubtitleTrack(i64),
    SelectVideoTrack(i64),
    SetSubtitleVisible(bool),
    LoadExternalSubtitle(PathBuf),
    SetSubtitleDelay(f64),
    SetSubtitleScale(f32),
    SetSubtitleVerticalPosition(u8),
    TakeScreenshot(PathBuf),
    StepFrame(FrameStepDirection),
    SetVideoAdjustment(VideoAdjustmentKind, i16),
    ResetVideoAdjustments,
    SetVideoFilterPreset(VideoFilterPreset),
}
